name = "VariationalH3M"
uuid = "be869012-f1ee-4d1b-ac0c-66b7016f7c90"
authors = ["Maxime Mouchet <max@maxmouchet.com>"]
version = "0.1.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HMMBase = "b2b3ca75-8444-5ffa-85e6-af70e2b64fe7"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
ArgCheck = "1.0"
Distributions = "0.20,0.21"
HMMBase = "1.0"
StatsFuns = "0.8,0.9"
julia = "1.2"
